#
# This makefile is intended for use with dmake(1) on Apple IIGS
#

# Program name
PROG = morse
OPTIMIZE = 79
STACK = 512 

# Delivery directory
BINDIR = /usr/bin
HAS_BSD_MANPAGE = true
CHAPTER=6
NEWSFX=6
OLDSFX=6G

.INCLUDE:	/src/gno/prog.mk
